import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'
import Provider from "../app/component/provider/Provider"
// import { UserProvider } from '@auth0/nextjs-auth0/client';
import ToasterContext from "../app/component/ToasterContext"


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
    
      <body className={inter.className}>
      <Provider>
      <ToasterContext/>
      <div className='text'>
      <Header/>
      </div>
    
      {children}
      </Provider>
      </body>
     
    
    </html>
  )
}
