"use client"
import { SessionProvider } from 'next-auth/react'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <SessionProvider>
   
      <body className={inter.className}>
      <div className='text'>
      <Header/>
      </div>
      {children}
      
      </body>
      </SessionProvider>
    </html>
  )
}
